language: ruby
sudo: required
dist: xenial
cache: bundler

addons:
  apt:
    packages:
    - wrk
    - apache2-utils

after_success:
  - bundle exec rake benchmark:compare

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
    - rvm: rbx-3
